import React, { useState } from 'react';
import { motion } from 'framer-motion';
import {
  FileText,
  Download,
  Copy,
  Check,
  Loader2,
  AlertTriangle,
  FileCheck2,
  Sparkles
} from 'lucide-react';

export default function ReportMarkdownTab({ report, datasetId }) {
  const [downloading, setDownloading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [downloadError, setDownloadError] = useState(null);

  if (!report) return null;

  const handleDownloadPDF = async () => {
    setDownloading(true);
    setDownloadError(null);
    try {
      const apiBase = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
      const targetId = datasetId || report?.dataset_id || 'export';
      let res = await fetch(`${apiBase}/api/dataset/${targetId}/report/pdf`);

      // If GET returns 404 or fails, fallback to POSTing the report object directly
      if (!res.ok && report) {
        res = await fetch(`${apiBase}/api/dataset/report/pdf`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(report),
        });
      }

      if (!res.ok) {
        throw new Error(`Failed to download PDF (${res.status} ${res.statusText})`);
      }

      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `analysis_report_${targetId}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error('PDF download error:', err);
      setDownloadError(err.message || 'Failed to download PDF');
    } finally {
      setDownloading(false);
    }
  };

  const handleCopyMarkdown = () => {
    if (report.markdown_report) {
      navigator.clipboard.writeText(report.markdown_report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="space-y-6"
    >
      {/* Action Header Card */}
      <div className="glass-card p-6 md:p-8 rounded-3xl shadow-glass border border-[#CEAB93]/50 flex flex-col sm:flex-row sm:items-center justify-between gap-5">
        <div className="space-y-1">
          <div className="flex items-center space-x-2">
            <span className="text-xs font-mono uppercase px-2.5 py-0.5 rounded-full bg-[#AD8B73]/15 text-[#3E2723] border border-[#CEAB93]/60 font-bold">
              Formal Executive Report
            </span>
            <span className="text-xs text-[#7D5A44] font-mono">
              Dataset ID: {datasetId || report.dataset_id}
            </span>
          </div>
          <h3 className="text-xl md:text-2xl font-extrabold text-[#3E2723] font-display">
            Executive Briefing Document
          </h3>
          <p className="text-xs text-[#7D5A44]">
            Export or inspect the complete C-suite analysis document generated by the multi-agent system.
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center space-x-2 px-4 py-3 rounded-2xl bg-white/80 border border-[#CEAB93]/50 text-[#3E2723] font-bold text-xs hover:bg-white transition-all shadow-sm cursor-pointer"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-600" />
                <span className="text-emerald-700">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 text-[#AD8B73]" />
                <span>Copy Markdown</span>
              </>
            )}
          </button>

          <button
            onClick={handleDownloadPDF}
            disabled={downloading}
            className="flex items-center space-x-2 px-5 py-3 rounded-2xl bg-gradient-to-r from-[#AD8B73] to-[#3E2723] text-white font-bold text-xs hover:from-[#3E2723] hover:to-[#2C1810] shadow-md shadow-[#AD8B73]/30 transition-all cursor-pointer disabled:opacity-50"
          >
            {downloading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Rendering PDF...</span>
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                <span>Download Executive PDF</span>
              </>
            )}
          </button>
        </div>
      </div>

      {downloadError && (
        <div className="p-4 rounded-2xl bg-red-50 border border-red-200 text-red-700 text-xs flex items-center space-x-2.5 shadow-sm">
          <AlertTriangle className="w-4 h-4 flex-shrink-0" />
          <span className="font-semibold">{downloadError}</span>
        </div>
      )}

      {/* Structured Sections Reader */}
      <div className="glass-card p-6 md:p-10 rounded-3xl shadow-glass border border-[#CEAB93]/50 space-y-8 text-[#3E2723]">
        {report.sections?.map((sec, sIdx) => (
          <div key={sec.id || `sec-${sIdx}`} className="space-y-3 pb-8 border-b border-[#CEAB93]/30 last:border-none last:pb-0">
            <h4 className="text-lg font-extrabold text-[#3E2723] font-display">
              {sec.title}
            </h4>
            <p className="text-xs text-[#7D5A44] italic font-medium">
              {sec.summary}
            </p>
            <div className="text-xs md:text-sm text-[#3E2723] leading-relaxed whitespace-pre-line bg-white/70 p-5 md:p-6 rounded-2xl border border-[#CEAB93]/40 font-sans shadow-inner">
              {sec.markdown_content}
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}
